instance creation
new

	self error: ['Use one of my factories to instantiate me'].